namespace Ramen.AgentTools;

using System.IO;
using Ramen.Game;

public static class TrainingRunAnalysis
{
    /// <summary>
    /// Analyze a training run. Takes a directory of agent snapshots generated by training,
    /// loads each snapshot in order, plays a batch of games with the agent at that snapshot,
    /// and uses all provided analyzers to analyze the played games.
    /// </summary>
    public static CSVBuilder Analyze(string runName, Func<string, IAgent> agentLoader, int sampleSize = 256, params ITrainingRunAnalyzer[] analyzers)
    {
        CSVBuilder output = new();
        string baseDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Ramen", "Weights", runName);
        if (!Directory.Exists(baseDir))
            return output;

        string[] files = Directory.GetFiles(baseDir, "*.bin");
        List<(int step, string filePath)> stepFiles = [];
        for (int i = 0; i < files.Length; i++)
        {
            string filePath = files[i];
            string fileName = Path.GetFileNameWithoutExtension(filePath);
            if (int.TryParse(fileName, out int step))
                stepFiles.Add((step, filePath));
        }

        stepFiles.Sort((left, right) => left.step.CompareTo(right.step));

        for (int i = 0; i < stepFiles.Count; i++)
        {
            (int step, string filePath) = stepFiles[i];
            IAgent agent = agentLoader(filePath);

            try
            {
                GameState[] games = PlayGameBatch(agent, sampleSize);
                output.NextRow().SetCell("step", step);
                for (int analyzerIndex = 0; analyzerIndex < analyzers.Length; analyzerIndex++)
                    analyzers[analyzerIndex].Analyze(games, output);
            }
            finally
            {
                if (agent is IDisposable disposableAgent)
                    disposableAgent.Dispose();
            }
        }

        return output;
    }

    static GameState[] PlayGameBatch(IAgent agent, int sampleSize)
    {
        int gameCount = Math.Max(0, sampleSize);
        GameState[] games = new GameState[gameCount];

        // Create all game states up front so policy evaluation can be batched across them.
        for (int i = 0; i < gameCount; i++)
            games[i] = new(GameData.Default);

        // Repeatedly perform one batched move until all games are finished.
        while (true)
        {
            bool allGamesDone = true;
            for (int i = 0; i < games.Length; i++)
            {
                if (!agent.IsGameDone(games[i]))
                {
                    allGamesDone = false;
                    break;
                }
            }

            if (allGamesDone)
                break;

            agent.MakeMove(1f, annotatePolicy: true, games);
        }

        return games;
    }
}
