<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agents\AgentTools.csproj" />
    <ProjectReference Include="..\AI\AI.csproj" />
    <ProjectReference Include="..\Game\Game.csproj" />
    <ProjectReference Include="..\Training\Training.csproj" />
  </ItemGroup>

</Project>
