namespace Ramen.Training;

using System;
using System.Collections.Generic;
using System.IO;
using Ramen.AI;
using Ramen.Game;

public interface ITrainingRunAnalyzer
{
    public void Analyze(IPolicyModel model, IEnumerable<GameState> games, CSVBuilder output);
}

public static class TrainingRunAnalysis
{
    /// <summary>
    /// Analyze a training run. Takes a directory of model weight snapshots generated by <see cref="ITrainingRun.Run"/>,
    /// loads each snapshot in order, plays a batch of games with the model at that snapshot,
    /// and uses all provided analyzers to analyze the played games.
    /// </summary>
    public static CSVBuilder Analyze(string runName, int sampleSize = 256, params ITrainingRunAnalyzer[] analyzers)
    {
        // Find the directory containing the model weight snapshots.
        CSVBuilder output = new();
        string baseDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Ramen", "Weights", runName);
        if (!Directory.Exists(baseDir))
            return output;

        // find the paths and step number for each snapshot, then sort them by step number
        string[] files = Directory.GetFiles(baseDir, "*.bin");
        List<(int step, string filePath)> stepFiles = [];
        for (int i = 0; i < files.Length; i++)
        {
            string filePath = files[i];
            string fileName = Path.GetFileNameWithoutExtension(filePath);
            if (int.TryParse(fileName, out int step))
                stepFiles.Add((step, filePath));
        }
        stepFiles.Sort((left, right) => left.step.CompareTo(right.step));

        // for each snapshot, load the model, play a batch of games, and analyze the results with each analyzer.
        for (int i = 0; i < stepFiles.Count; i++)
        {
            (int step, string filePath) = stepFiles[i];
            IPolicyModel model = new PolicyModel();
            model.Load(filePath);
            GameState[] games = PlayGameBatch(model, sampleSize);

            output.NextRow().SetCell("step", step);
            for (int analyzerIndex = 0; analyzerIndex < analyzers.Length; analyzerIndex++)
            {
                ITrainingRunAnalyzer analyzer = analyzers[analyzerIndex];
                analyzer.Analyze(model, games, output);
            }
        }

        return output;
    }

    static GameState[] PlayGameBatch(IPolicyModel model, int sampleSize)
    {
        int gameCount = Math.Max(0, sampleSize);
        GameState[] games = new GameState[gameCount];
        PolicyOnlyAgent agent = new(model);

        // Create all game states up front so policy evaluation can be batched across them.
        for (int i = 0; i < gameCount; i++)
            games[i] = new(GameData.Default);

        // Repeatedly perform one batched move until all games are finished.
        while (true)
        {
            bool allGamesDone = true;
            for (int i = 0; i < games.Length; i++)
            {
                if (!agent.IsGameDone(games[i]))
                {
                    allGamesDone = false;
                    break;
                }
            }

            if (allGamesDone)
                break;

            agent.MakeMove(1f, annotatePolicy: true, games);
        }

        return games;
    }
}
